- name: debian unstable repository is enabled
  apt_repository:
    repo: deb http://deb.debian.org/debian/ unstable main
    state: present

- name: debian unstable repository is de-prioritized
  copy:
    content: |
      Package: *
      Pin: release a=unstable
      Pin-Priority: 90
    dest: /etc/apt/preferences.d/limit-unstable

- name: dkms and linux headers are installed
  apt:
    name:
      - dkms
      - linux-headers-{{ ansible_kernel }}
    state: present

- name: wireguard is installed
  apt:
    name: wireguard
    state: present

- name: wireguard service port is registered
  lineinfile:
    path: /etc/services
    line: "{{ wireguard_interface }} {{ wireguard_port }}/udp"
    regexp: "^{{ wireguard_interface }} "
    state: present

- name: wireguard server configuration is up
  template:
    src: wireguard-server.conf.j2
    dest: /etc/wireguard/{{ wireguard_interface }}.conf
    mode: 0600
  notify: restart wg-quick

- name: wireguard client configurations are generated
  template:
    src: wireguard-client.conf.j2
    dest: _wireguard-client-{{ client.node_id }}-{{ client.name }}.conf
  connection: local
  become: no
  loop: "{{ wireguard_clients }}"
  loop_control:
    loop_var: client

- name: ipv4 forwarding is enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    reload: yes

- name: wireguard kernel module is loaded
  modprobe:
    name: wireguard
    state: present

- name: wg-quick is activated
  service:
    name: wg-quick@{{ wireguard_interface }}
    state: started
    enabled: yes
