- name: admin pubkeys are in sync
  copy:
    content: "{{ admin_pubkeys | join('\n') }}"
    dest: .ssh/authorized_keys
    mode: 0600
  become: no

- name: apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 86400
