VM_BOX = "debian/buster64"
VM_CPUS = 1
VM_MEMORY = 512

Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.provider :virtualbox do |v|
    v.cpus = VM_CPUS
    v.memory = VM_MEMORY
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provision.yml"
  end
end
