#!/bin/sh -eu

host="localhost"

while getopts t: opt; do
    case ${opt} in
    t)  host="${OPTARG}"
        ;;
    ?)  exit 1
    esac
done

shift $((OPTIND - 1))

src="$1"
dest="$2"

ansible -o -c local -m template -a "src='${src}' dest='${dest}'" "${host}"
