#!/bin/sh -eu

export ANSIBLE_LOAD_CALLBACK_PLUGINS=True
export ANSIBLE_STDOUT_CALLBACK=json

host="$1"
template="$2"

ansible -c local -m debug -a msg="${template}" "${host}" |
jq -r ".plays[0].tasks[0].hosts | to_entries[0].value.msg | @text"
